# Generated by Django 4.1.5 on 2023-01-28 15:00

from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('printer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file_pdf',
            field=models.FileField(blank=True, null=True, upload_to=pathlib.PureWindowsPath('Q:/Dokumenty/!Studia/!Projects/kalinka_printer/printer/uploads/pdf')),
        ),
        migrations.AlterField(
            model_name='document',
            name='mono',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='pages',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
