# Generated by Django 4.1.5 on 2023-01-28 15:41

from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('printer', '0002_alter_document_file_pdf_alter_document_mono_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='file_org',
        ),
        migrations.RemoveField(
            model_name='document',
            name='file_pdf',
        ),
        migrations.AddField(
            model_name='document',
            name='editable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='document',
            name='file',
            field=models.FileField(default=0, upload_to=pathlib.PureWindowsPath('Q:/Dokumenty/!Studia/!Projects/kalinka_printer/printer/uploads')),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='ready_to_print',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='document',
            name='orientation',
            field=models.CharField(choices=[('P', 'Pionowa'), ('L', 'Pozioma')], default='P', max_length=1),
        ),
    ]
